spring:
  application:
    name: login-service
  datasource:
    url: jdbc:mysql://localhost:3306/microservices_demo    
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update      
    properties:
     hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    
server:
  port: 8081



